name: Security Audit

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Run cargo-audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
