name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-gnu, linux-musl, win-gnu, win-msvc, win32-msvc, macos]
        include:
          - build: linux-gnu
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - build: linux-musl
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - build: win-gnu
            os: windows-2025
            target: x86_64-pc-windows-gnu
          - build: win-msvc
            os: windows-2025
            target: x86_64-pc-windows-msvc
          - build: win32-msvc
            os: windows-2025
            target: i686-pc-windows-msvc
          - build: macos
            os: macos-15-intel
            target: x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies (linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            --allow-unauthenticated xvfb libx11-dev libxrandr-dev
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check the project files
        run: cargo check --locked --target ${{ matrix.target }}
      - name: Check the lints
        run: cargo clippy --locked --tests --target ${{ matrix.target }} -- -D warnings
      - name: Run tests (macos/windows)
        if: startsWith(matrix.os, 'macos-') || startsWith(matrix.os, 'windows-')
        run: |
          cargo test --verbose --features test-ws
      - name: Install cargo-tarpaulin (linux)
        if: matrix.build == 'linux-gnu'
        run: |
          curl -s https://api.github.com/repos/xd009642/tarpaulin/releases/latest | \
            grep "browser_download_url.*x86_64-unknown-linux-musl.tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
          tar -xzf cargo-tarpaulin-*.tar.gz
          mv cargo-tarpaulin ~/.cargo/bin/
      - name: Run tests (linux)
        if: matrix.build == 'linux-gnu'
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24" \
            cargo tarpaulin -o Xml -v --features test-ws -- --test-threads 1
      - name: Upload reports to Codecov (linux)
        if: matrix.build == 'linux-gnu'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
          flags: unit-tests
          name: code-coverage-report
          fail_ci_if_error: true

  rustfmt:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check the formatting
        run: cargo fmt --all -- --check --verbose

  msrv:
    name: Minimum Rust version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxrandr-dev
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.88
      - name: Check MSRV
        run: cargo check --locked --all-features

  lychee:
    name: Check the links
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --exclude "twitter.com|crates.io|aur.archlinux.org/(.+?).git|patreon.com|mailto:+|%7Busername%7D" -v *.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
